"""
Test the saturation argument: for enumerable f, how many matrices in SL_2(N_0) have
chi(A) in window [n_0, n_0 + k], and what's the relationship to compositeness?

Specifically: enumerate matrices by word length, count cross-terms in windows.
"""

def isprime(n):
    n = abs(n)
    if n < 2: return False
    if n < 4: return True
    if n % 2 == 0: return False
    i = 3
    while i*i <= n:
        if n % i == 0: return False
        i += 2
    return True

def tau(n):
    n = abs(n)
    if n == 0: return 0
    cnt = 0
    i = 1
    while i*i <= n:
        if n % i == 0:
            cnt += 1
            if i*i != n:
                cnt += 1
        i += 1
    return cnt

def phi0(n): return n*n + 1

# Generate SL_2(N_0) matrices up to word length L by tree expansion
# S = [[1,0],[1,1]], T = [[1,1],[0,1]]
# Multiplying on left.
import itertools

def chi(A):
    """For phi_0 enumeration: chi(A) = ac + bd where A = [[a,b],[c,d]]."""
    (a, b), (c, d) = A
    return a*c + b*d

def m_phi0(A):
    """First component: m = a^2 + b^2."""
    (a, b), (c, d) = A
    return a*a + b*b

def matmul(M1, M2):
    (a1, b1), (c1, d1) = M1
    (a2, b2), (c2, d2) = M2
    return ((a1*a2 + b1*c2, a1*b2 + b1*d2), (c1*a2 + d1*c2, c1*b2 + d1*d2))

S = ((1, 0), (1, 1))
T = ((1, 1), (0, 1))
I = ((1, 0), (0, 1))

def all_matrices_up_to_length(L):
    """Generate all matrices of word length 0..L by BFS tree expansion."""
    # Note: tree from root I, left child = S * A, right child = T * A
    yield I
    cur = [I]
    for level in range(1, L+1):
        next_level = []
        for A in cur:
            next_level.append(matmul(S, A))
            next_level.append(matmul(T, A))
        cur = next_level
        for A in cur:
            yield A

# Sanity: max chi in length L
for L in [3, 5, 7, 10, 12, 15]:
    chis = [chi(A) for A in all_matrices_up_to_length(L)]
    print(f"  L={L}: total matrices = {len(chis)}, max chi = {max(chis)}, distinct chi values = {len(set(chis))}")

print("\n" + "="*70)
print("WINDOW [10, 30] for phi_0: how many matrices have chi in window?")
print("="*70)
n0, n1 = 10, 30
matrices_in_window = []
for A in all_matrices_up_to_length(15):
    if n0 <= chi(A) <= n1:
        matrices_in_window.append(A)

# Group by chi value
by_chi = {}
for A in matrices_in_window:
    c = chi(A)
    by_chi.setdefault(c, []).append(A)

print(f"\nTotal matrices with chi in [{n0}, {n1}]: {len(matrices_in_window)}")
print(f"\nFor each n in window:")
print(f"  {'n':>3} {'tau(f(n))':>10} {'# matrices':>12} {'f(n)':>8} {'prime?':>8}")
total_tau = 0
for n in range(n0, n1+1):
    fn = phi0(n)
    t = tau(fn)
    total_tau += t
    nm = len(by_chi.get(n, []))
    print(f"  {n:>3} {t:>10} {nm:>12} {fn:>8} {'YES' if isprime(fn) else 'no':>8}")
    assert nm == t, f"BIJECTION FAILED at n={n}: tau={t} but matrices={nm}"

print(f"\n  Sum of tau(f(n)) over n in [{n0}, {n1}] = {total_tau}")
print(f"  Total matrices in window = {len(matrices_in_window)}")
print(f"  These are EQUAL by the Shakov bijection. ✓")

print("\n" + "="*70)
print("KEY OBSERVATION: word lengths of matrices in window")
print("="*70)
length_dist = {}
for A in matrices_in_window:
    # find word length: number of S/T-multiplications to reach A from I.
    # By construction we generated by length, but let's verify by entry size.
    (a, b), (c, d) = A
    # Lower bound on length: max entry's "Fibonacci index"
    max_e = max(a, b, c, d)
    length_dist.setdefault(max_e, 0)
    length_dist[max_e] += 1

print(f"  Distribution of max entry value (proxy for word length):")
for me in sorted(length_dist.keys())[:15]:
    print(f"    max entry = {me}: {length_dist[me]} matrices")
